-- AGGREGATE FUNCTIONS

-- COUNT
-- This query counts the total number of rows (students) in the table
SELECT COUNT(*) FROM students;


-- AVG (Average)
-- This query calculates the average marks of all students
SELECT AVG(marks) FROM students;


-- MAX
-- This query returns the highest marks from the Students table
SELECT MAX(marks) FROM students;


-- MIN
-- This query returns the lowest marks from the Students table
SELECT MIN(marks) FROM students;
